DROP USER has_many_user;

CREATE USER has_many_user;

DROP DATABASE has_many_blogs;

CREATE DATABASE has_many_blogs WITH OWNER = has_many_user;

DROP TABLE IF EXISTS users;

CREATE TABLE users(
	id SERIAL PRIMARY KEY NOT NULL,
	username VARCHAR(90) NOT NULL,
	first_name VARCHAR(90) DEFAULT NULL,
	last_name VARCHAR(90) DEFAULT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

DROP TABLE IF EXISTS posts;

CREATE TABLE posts(
	id SERIAL PRIMARY KEY NOT NULL,
	title VARCHAR(180) DEFAULT NULL,
	url VARCHAR(510) DEFAULT NULL,
	content TEXT DEFAULT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE comments(
	id SERIAL PRIMARY KEY NOT NULL,
	body VARCHAR(510) DEFAULT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE posts
ADD COLUMN user_id SERIAL NOT NULL;

ALTER TABLE posts
ADD FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE comments
ADD COLUMN user_id SERIAL NOT NULL;

ALTER TABLE comments
ADD FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE comments
ADD COLUMN posts_id SERIAL NOT NULL;

ALTER TABLE comments
ADD FOREIGN KEY (posts_id) REFERENCES posts(id);