CREATE USER has_many_user;

CREATE DATABASE has_many_blogs WITH OWNER = has_many_user;

DROP TABLE IF EXISTS users;

CREATE TABLE users(
	id SERIAL PRIMARY KEY NOT NULL,
	username VARCHAR(90) NOT NULL,
	first_name VARCHAR(90) DEFAULT NULL,
	last_name VARCHAR(90) DEFAULT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

DROP TABLE IF EXISTS posts;

CREATE TABLE posts(
	id SERIAL PRIMARY KEY NOT NULL,
	body VARCHAR(510) DEFAULT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

DROP TABLE IF EXISTS comments;

CREATE TABLE comments(
	id SERIAL PRIMARY KEY NOT NULL,
	body VARCHAR(510) DEFAULT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE posts
ADD user_id INTEGER NOT NULL REFERENCES users(id);

ALTER TABLE comments
ADD user_id INTEGER NOT NULL REFERENCES users(id);

ALTER TABLE comments
ADD posts_id INTEGER NOT NULL REFERENCES posts(id);